module.exports.descriptors = [
    "ancient",
    "blasphemous",
    "unthinkable",
    "healthy",
    "decent",
    "cosy",
    "fascinating",
    "terminally",
    "exciting",
    "cozy",
    " expensive",
    "modestly",
    "rocky",
    "abiding",
    "horrible",
    "usual",
    "sore",
    "ominously",
    "cramped",
    "prettily"
]

module.exports.places = [
    "Allotment",
    "Amberfield land",
    "Ancient woodland",
    "Beach",
    "Conurbation",
    "County wildlife site",
    "Court",
    "Cul-de-sac",
    "Cultural quarter",
    "Designated area",
    "Entrapment place",
    "Heritage coast",
    "Land",
    "Local green space",
    "Local site",
    "Megacity",
    "National nature reserves",
    "National park",
    "Park",
    "Safeguarded land",
    "Smart city",
    "Town",
    "Village",
    "Village greens",
    "Wetlands",
    "Wood",
    "World heritage site",
]
